### ISSUE TITLE
iOS: "accessToken must be a valid string object" 

### ISSUE THREAD

**Issue by liemdo** [twilio/twilio-voice-react-native#117]
When I pass in the accessToken to the `voice.register(...)` method, it works fine on Android. However, I get the error "accessToken must be a valid string object" on iOS. Here is the screenshot of the error showing on the expo client with the valid token:

![z3985210403503_c6d14baf785005fd966506e60f5f3d6f](https://user-images.githubusercontent.com/989817/209617240-a44f9103-7bd9-4ffe-917a-248996dc5622.jpg)

**Comment by bobiechen-twilio** [comment]
Thanks for reaching out @liemdo.

I believe this is a typo in the [iOS SDK](https://github.com/twilio/twilio-voice-ios) - very likely it is complaining about the device token of the iOS PushKit framework being missing.
Please check the iOS app project and make sure the [TwilioVoicePushRegistry instance](https://github.com/twilio/twilio-voice-react-native/blob/main/test/app/ios/TwilioVoiceReactNativeExample/AppDelegate.m#L60-L62) is initialized in the frontmost object (usually the `AppDelegate` object).

-bobie

**Comment by liemdo** [comment]
I have added that but I still see the same error. Is there anything else I need to add to the ios/ folder?

**Comment by bobiechen-twilio** [comment]
Thanks @liemdo 

If the `TwilioVoicePushRegistry` object is correctly initialized, your app should hit [this callback](https://github.com/twilio/twilio-voice-react-native/blob/main/ios/TwilioVoicePushRegistry.m#L44) and receive the PushKit device token so the iOS SDK can use for push notification registration.

To make sure PushKit is properly initialized, you should see a valid value if you set a breakpoint at the [voice_register()](https://github.com/twilio/twilio-voice-react-native/blob/main/ios/TwilioVoiceReactNative.m#L431) method.

Please note that APNS only works for devices. PushKit will not provide a device token if the application is running on a simulator.

**Comment by liemdo** [comment]
The app installed TwilioVoice 6.5.0 and it caused the issue. When I specify the version of TwilioVoice to be 6.4.7, I don't see the error anymore.

**Comment by bobiechen-twilio** [comment]
Hi @liemdo 

Can you share how the version is updated, i.e. which file did you modify? 6.4.7 does not seem to match any of the Twilio Voice Android/iOS/JavaScript/React Native SDK.

**Comment by liemdo** [comment]
Sorry. I meant `6.4.3` in Podfile.

**Comment by liemdo** [comment]
Actually, the issue still persists. It just happens randomly. I can open the app to make & receive calls. However, the app crashes sometimes with the error above. We're using an ejected expo 46.

**Comment by bobiechen-twilio** [comment]
I tried installing the Voice iOS SDK 6.5.0 and was able to use the register & connect method without any issue.
Is it possible to add debugging logs in your app and print the access token (and device token if it's the voice_register method) when the exception happens?

**Comment by liemdo** [comment]
It seems the device token can't be obtained if I run the app using Expo custom dev client on a real device: https://docs.expo.dev/development/create-development-builds/. When I log the device token, it's `null.` I don't get any other errors with other native packages. 

However, I don't get the error if I run the release build.

**Comment by cpham-rb** [comment]
I built a version to run on real device for testing, the first run after app installed is ok, I can run `voice.register` without error.
But when I close the app and open it again, I encountered error with `voice.register`

![z4018727925592_ee858e300ecd8ae2cbd19bb4eabadb96](https://user-images.githubusercontent.com/58545551/211016759-ed7d3810-5ac4-4d41-aa4d-fcf2bde337dd.jpg)

and result returned by `voice.getDeviceToken()` is empty

---
- I tested on 2 phones: iPhone 6 - iOS 12.5.6, iPhone X iOS 16.03
- I restart the phone and open the app, sometimes `voice.getDeviceToken()` return result and I can run `voice.register` without error.

**Comment by liemdo** [comment]
@bobiechen-twilio 

When I debug the code, the `self.deviceToken` is set only once here:  https://github.com/twilio/twilio-voice-react-native/blob/main/ios/TwilioVoiceReactNative.m#L118

When the app is killed and reopened, the RN function`voice.getDeviceToken()` doesn't return the device token. It should return the device token all the time. Can you check and fix this issue?

**Comment by bobiechen-twilio** [comment]
@liemdo Thanks for the update.
Is your TwilioVoicePushRegistry instance initialized at app launch as shown in the [example application](https://github.com/twilio/twilio-voice-react-native/blob/main/test/app/ios/TwilioVoiceReactNativeExample/AppDelegate.m#L60-L62)? This is very important especially when the app is not running and woken up by a VoIP push notification - the app needs to initialize the iOS PushKit instance immediately in order to handle the push notification and present the call to the user.

**Comment by liemdo** [comment]
Yes, I do have TwilioVoicePushRegistry instance initialized. The app can make & receive calls just first right after I install it. However, if I kill the app as I mentioned and reopen it, I get the error because `voice.getDeviceToken()` returns null.

**Comment by bobiechen-twilio** [comment]
This is a bit bizarre since the iOS SDK will always return a valid string, either the actually device token from PushKit (note that this is only available on actual devices) or an empty string: https://github.com/twilio/twilio-voice-react-native/blob/main/ios/TwilioVoiceReactNative.m#L416-L429
By the way, the iOS app should not have to call `voice.getDeviceToken()`  before calling `voice.register()` - the iOS SDK takes care of the PushKit device token if the `TwilioVoicePushRegistry` instance is initialized properly.

**Comment by liemdo** [comment]
@bobiechen-twilio I could reproduce this with the example app also.

### Steps to reproduce with a real device using Debug scheme:
1. When viewing the app, Reload the app from the Debugger
2. Tap Register and observe the access token error

https://user-images.githubusercontent.com/989817/211695743-4909d63b-f6e9-4df9-b3d3-abafb5c4eb51.MP4


### The release version also crashes sometimes when I kill & restart the app and tap on Register


https://user-images.githubusercontent.com/989817/211695826-f86cf1ca-1ced-43d7-9952-21de33849710.mov

**Comment by bobiechen-twilio** [comment]
Thanks @liemdo.
I can reproduce the first case (reloading app from the bundle) - I thought it only reloads the bundle, not the iOS app itself, but somehow the instance variable (the device token) of the iOS app is no longer available. I guess it should be okay for this case since end users won't be able to refresh this way.

For the release version, most likely the iOS SDK has not received the device token from the PushKit framework. This could be a corner case in my opinion unless the app automatically calls the registration method at launch every time (I'd imagine the user has to go through some log-in sequence before calling the SDK registration method). However I'll still add something to at least prevent the exception from happening.

**Comment by bobiechen-twilio** [comment]
@liemdo #125 is in. Let us know how it goes with the fix.
Thanks again for filing the issue.
