### ISSUE TITLE
I don't see a button to hang off the call

### ISSUE THREAD

**Issue by isaacVzz** [twilio/twilio-voice-react-native#118]
When I make an outgoing call on IOS devices, I just see a green bar in the top corner of my app and I can't open this. I want to see the duration time of the call and a button to hang off it. 

![WhatsApp Image 2022-12-27 at 21 10 35](https://user-images.githubusercontent.com/52250577/209751472-58742401-df50-4bb8-91ef-000ea8a08f1f.jpeg)

**Comment by bobiechen-twilio** [comment]
Hi @isaacVzz 

The iOS SDK uses the iOS CallKit framework to provide the best call experience. It gets the system Call UI for free when it receives an incoming call. The application is still responsible of the UI components in case the call is an outbound call initiated by the app. In fact application call UI is always needed since you can still tap on the app button in the system Call UI from an incoming call and go back to the app UI, where necessary UI components should be presented for the users.

The SDK provides a set of Call events: https://github.com/twilio/twilio-voice-react-native/blob/main/src/Call.tsx#L34. The application can use the events and create the desired user experience, for example you can start a timer when you receive the `connected` event and update the UI with the duration.

**Comment by isaacVzz** [comment]
Hi @bobiechen-twilio 
Sorry for my late reply, I've been busy integrating a contact center with Twilio Flex these days. 

I see in this case when is an outbound call initiated by the app and I tap the app call button this doesn't do anything, In this case I need to build my own Call UI with my own react-native components? 

Another question, I'm looking for a React Native SDK for Twilio Conversation, I'm developing a contact center with Flex Conversations and I want Integrate a Chat service on our mobile app. 
I'm  following the next Twilio guide to configure my chat addresses 
https://www.twilio.com/docs/flex/admin-guide/setup/conversations/manage-conversations-chat-addresses

Do u know If Twilio counts with some SDK for React-Native that could you help me to integrate this chat to my mobile app ?

**Comment by isaacVzz** [comment]
Hi @bobiechen-twilio  Happy New Year!
First I hope you've enjoyed the holidays, just for ask about my last reply

**Comment by liemdo** [comment]
@isaacVzz You have to build everything by yourself. You can use this package https://github.com/FaridSafi/react-native-gifted-chat to build the chat app

**Comment by isaacVzz** [comment]
@liemdo how can I know when the state of the call change without use a setInterval for check the value each second? 
setInterval(
       ()=> console.log(call.getState()) , 1000
)

**Comment by liemdo** [comment]
You can listen to many events emitted by the SDK including the `Disconnected` one: https://github.com/twilio/twilio-voice-react-native/blob/5621077f2c580aefa4b1631bfe702c672d66709a/api/voice-react-native-sdk.api.md

**Comment by isaacVzz** [comment]
@liemdo how can I listen this events?

**Comment by mhuynh5757** [comment]
Hi all, thanks for the community discussion. It seems like the issue has been answered, I'm going to close this for now. Please feel free to reach out if you need further assistance.
