### ISSUE TITLE
Call not stopping when closing the app

### ISSUE THREAD

**Issue by helene-bieber** [twilio/twilio-voice-react-native#147]
On iOS, when making outbound call, I understood that I have to implement my own UI for disconnecting the call and that is working. But if I am closing the app during the call, the call is still going on and I don't have my button to disconnect the call as the app is closed. Also while the call is still going on, there is no way for the user to know that.  Is there a way to prevent that or is it a bug in my code?

**Comment by bobiechen-twilio** [comment]
Hi @helene-bieber 

Thanks for reaching out.
I am afraid this has been a system behavior that is difficult for the iOS SDK to work around. When the application is being terminated, there is only a very short amount of time that the app or the SDK can react upon receiving the `applicationWillTerminate` notification from system. Since most of the SDK operations are asynchronous including `disconnect()`, it appears that this is not enough for the SDK to properly disconnect the call before the process is killed, and there is no way to let Twilio or the other call parties to know whether you are muted or disconnected like you have observed, and eventually the call will be ended by Twilio if no audio packets are detected for longer than 1 minute.

Hope this makes sense and sorry for the inconvenience.
