### ISSUE TITLE
How to ignore calls?

### ISSUE THREAD

**Issue by dianamariand92** [twilio/twilio-voice-react-native#153]
Hi, I would like to know if it is possible to ignore specific calls from a number (a from) on a specific device. I know there is a reject() method in the callInvite class, but even in this way the badge of the incoming call is shown but then it disappears. Also if the application has been killed, it continues to receive the call and is not rejected with the reject() method.

Thanks.

**Comment by bobiechen-twilio** [comment]
Hi @dianamariand92 

The SDK does not have the capability to support programmatically ignoring (or accepting/rejecting) a call based on the caller. Once the call invite is raised to the application and the incoming call is shown to the end users, it's up to the user and the app in terms of what to do with it.

Things might also be slightly different by platforms - on Android most likely the app is presenting a toast-like notification showing the incoming call and options (reject or accept) to the user. There should be a way to programmatically cancel that notification. For iOS, since the React Native Voice SDK is integrated with the iOS CallKit framework, the whole incoming call experience is designed to look like a normal call. You can associate the iOS client identity to an existing contact on the device and block (I am not sure if there is another option to "just ignore"), but this will still require direct user actions.

Regarding the app still receiving notifications even when it's not running - once a mobile client is registered to receive incoming call push notifications, the app will always be able to receive incoming calls unless explicitly unregistered. I am curious about the part that you were not able to reject in this state - does your application call the `reject()` method at this state but the caller was not hung up and kept ringing?

-bobie

**Comment by dianamariand92** [comment]
Hi @bobiechen-twilio 

In the end, I was able to achieve my goal by modifying the specific library files and making a patch. Specifically, I modified the registry functions to pass the phones (from) from which I was interested in receiving calls from Twilio, I specifically modified the voice_register method of TwilioVoiceReactNative.m to store the phones in NSUserDefault and modified the callInviteReceived method in the TwilioVoicePushRegistry file. to check for those phones before issuing the NSNotificationCenter.

But regarding what you asked me, the react-native callInvite method is not invoked when the application is killed and it does not allow rejecting a call from a specific number. I suppose this happens because when the application is killed, the part that communicates with the operating system is the one related to iOS, not the react-native part.

Thank you very much for your reply. Now I plan to modify the android part to be able to do the same.

**Comment by bobiechen-twilio** [comment]
Thanks for the updates @dianamariand92 

Glad that you found the iOS component and added business logics that suit your use case 👍.

Just to confirm - when the app is terminated, it is not brought up and showing incoming call when a call is made to this client? if you are using the latest SDK from this repository, the component that handles the initialization and callback events of the iOS PushKit framework should be initialized as well as the React Native native module, and report the VoIP push notification to the iOS CallKit framework and eventually the incoming call. In case the VoIP push notification is not properly reported to CallKit as an incoming call, exception will be raised to the application, which might have resulted in what you have observed - the application was actually launched upon receiving the push notification from the system, but was terminated because it was not reporting call timely. ([Apple VoIP best practice](https://developer.apple.com/documentation/pushkit/responding_to_voip_notifications_from_pushkit?language=objc))

**Comment by dianamariand92** [comment]
Hi @bobiechen-twilio, 

The call does appear, but if in the react-native code I put a reject for a specific number, this method does not fire if the app was killed, it does fire if the app is in background or foregorund.

Also I am getting quite a few errors when I try to use the library in Android. I will open a new issue for this case.

Thank you for your answer and for all the work on this library.

**Comment by bobiechen-twilio** [comment]
The app should be launched by the incoming call push notification and given some time to perform actions, just like what you do when the app is running (active or backgrounded). Does the app get launched and show incoming calls when it was terminated (if the call is not rejected automatically by the app)?

In the case where the app was killed previously, If the app is not brought up by the incoming call, then the app is possibly terminated due to the policy violation I mentioned above.

**Comment by imranali51201** [comment]
@bobiechen-twilio is this package for expo because i am using it in expo and when some user wants to connect with some other user (client to client) and i dial the client from backend from twiml webhook but other user not receiving any invite in callInvite event.
Any idea?

**Comment by mhuynh5757** [comment]
Hi @imranali51201, thanks for reaching out. It seems like your issue is separate from the original. Please submit a new issue if you are still encountering problems.

I am closing this original issue as stale. Please feel free to reopen if the problem is still occurring.
