### ISSUE TITLE
IOS could't make a new call when have incoming call

### ISSUE THREAD

**Issue by congkhanh24** [twilio/twilio-voice-react-native#174]
Hi everyone!

I had an incoming call and couldn't make new outgoing call until that incoming call canceled only IOS, android was normal
voice.connect() does not return any errors

**Comment by bobiechen-twilio** [comment]
Hi @congkhanh24 thanks for reaching out.

The iOS part of the React Native Voice SDK is integrated with the iOS CallKit framework and I believe you might have seen a similar debugging message in Xcode which suggests that the app has reached maximum number of call groups.
```
Error Domain=com.apple.CallKit.error.requesttransaction Code=7
```

The default value of this option is 1, which is most likely the failure reason of the second call since there is already one active call. You can use the `setCallKitConfiguration` method of the Voice class ([see API doc](https://github.com/twilio/twilio-voice-react-native/blob/main/api/voice-react-native-sdk.api.md)) and increase the value of `callKitMaximumCallGroups` so you can have multiple calls simultaneously.

Please note that the app is responsible of managing the UI call state updates from different active calls.

**Comment by congkhanh24** [comment]
I checked and it worked well. thanks a lot! @bobiechen-twilio

**Comment by congkhanh24** [comment]
Hi @bobiechen-twilio 
I click any item on recents phone app and it open my app. Have any events to know them?

**Comment by bobiechen-twilio** [comment]
Hi @congkhanh24 

We've recently updated the RN SDK reference app repo and added the ability, as well as the instructions of configuring the app and source code, in order to support starting calls from the iOS call history: https://github.com/twilio/twilio-voice-react-native-app/pull/75.
