### ISSUE TITLE
Speaker/mute events from native call IOS screen to RN and vice versa

### ISSUE THREAD

**Issue by MykolaKobetiakCloudGenie** [twilio/twilio-voice-react-native#193]
I am developing the app using RN + Expo. IOS incoming and outgoing calls work well. But when I am turning on Speaker on the native screen how can I know on the app side that the speaker is turned on? The same question about mute.
From the app side when I am turning on the speaker by selecting the needed audio device native screen shows that the speaker is turned on. The same does not work with mute/unmute.

How can I handle this event?

**Comment by mhuynh5757** [comment]
Hi @MykolaKobetiakCloudGenie apologies for the late response. A lot has changed in the SDK since the time of original posting. Here's a link to the API documentation regarding knowing which audio devices are available and which one is selected: https://github.com/twilio/twilio-voice-react-native/blob/latest/docs/api/voice-react-native-sdk.voice_namespace.listener_namespace.audiodevicesupdated_typealias.md

You can check if a call is muted by using the `call.isMuted()` API: https://github.com/twilio/twilio-voice-react-native/blob/latest/docs/api/voice-react-native-sdk.call_class.ismuted_method.md
