### ISSUE TITLE
CallInvite.setCallHandle missing in beta.3?

### ISSUE THREAD

**Issue by treycucco** [twilio/twilio-voice-react-native#213]
# Issue

The [release notes] for 1.0.0-beta.3 mentions a new API for setting the call handle for incoming calls. I'm very eager for this feature! However, it does not appear that this actually made it in to the release. I've checked the code that's actually installed node_modules, and I do not see the `setCallHandle` method on `Call` or `CallInvite`.

If I grep the latest code for `setCallHandle` I do see the method mentioned in docs, but only in the docs and nowhere else.

Am I missing something obvious here, or did this feature somehow not make it into the release?

## Pre-submission Checklist
- [x] I have verified that the issue occurs with the latest release and is not marked as a known issue in the [CHANGELOG.md](https://github.com/twilio/twilio-voice-react-native/blob/main/CHANGELOG.md).
- [x] I reviewed the [Common Issues](https://github.com/twilio/twilio-voice-react-native/blob/main/COMMON_ISSUES.md) and open GitHub issues and verified that this report represents a potentially new issue.
- [x] I am not sharing any [Personally Identifiable Information (PII)](https://www.twilio.com/docs/glossary/what-is-personally-identifiable-information-pii)
       or sensitive account information (API keys, credentials, etc.) when reporting this issue.

## Description 

The `setCallHandle` method mentioned in the release notes does not seem to be available on `Call` or `CallInvite`.

## Reproduction Steps
1. Install 1.0.0-beta.3
2. Try to use the `setCallHandle` method. TypeScript will complain it doesn't exist
3. Check the code files in `node_modules`
4. The methods do not show up.

**Comment by bobiechen-twilio** [comment]
Hi @treycucco 

Thanks for reaching out.
Unfortunately there was a mistake that I forgot to update the PR description to reflect the final change and it eventually went into the changelog.

The SDK team did added a new API (`Voice.initializePushRegistry()`) to give applications the flexibility of defaulting to the SDK's iOS PushKit implementation or using their own. Please see [this](https://github.com/twilio/twilio-voice-react-native/blob/main/docs/applications-own-pushkit-handler.md) for details and examples.

In order for the incoming call UX to work properly when the iOS app is in the background or was previously terminated, both the push notification handling and CallKit incoming call reporting must happen in the Obj-C native layer in order to comply to the threading policy (violation will lead to app termination). That being said, you can still programmatically change the caller name/handle that is being reported to CallKit by modifying [ios/TwilioVoiceReactNative+CallKit.m](https://github.com/twilio/twilio-voice-react-native/blob/main/ios/TwilioVoiceReactNative%2BCallKit.m#L70) based on your business logic.

-bobie

**Comment by bobiechen-twilio** [comment]
Thanks @treycucco 

This looks like something we can achieve by the [CallKit reportCall()](https://developer.apple.com/documentation/callkit/cxprovider/1930703-reportcallwithuuid?language=objc) method. I've created a ticket for tracking and doing a spike to see how it works in action, especially when the app is backgrounded or terminated.

**Comment by kpchoy** [comment]
Please update to the latest version. The new api should cover this usecase. Please open another issue if you still experience problems.
