### ISSUE TITLE
call audio and microphone  not working when locks screen android or app in background .

### ISSUE THREAD

**Issue by GaganJatana55** [twilio/twilio-voice-react-native#290]
am using this sdk to make outgoing calls only for now , rest seems working but when talking press lock screen or put the app in bacground the audio and microphone stops working .resumes when open the app.

**Comment by afalls-twilio** [comment]
@GaganJatana55 Is this happening with the reference app?

My guess is that this probably due to your application not requesting those permissions from the user. if you look at the beta.4 example [here](https://github.com/twilio/twilio-voice-react-native/blob/b33546955426f4562a9f535f6257985f27247ede/test/app/android/app/src/main/java/com/example/twiliovoicereactnative/MainActivity.java#L13) you can see how that is being done.

**Comment by MykolaKobetiakCloudGenie** [comment]
The same issue. When the app foregrounds it is working fine. When the app is stopped it crashes with an error

java.lang.RuntimeException: Unable to start service com.twiliovoicereactnative.IncomingCallNotificationService@31b76a5 with Intent { act=ACTION_INCOMING_CALL cmp=com.whistle.dev/com.twiliovoicereactnative.IncomingCallNotificationService (has extras) }: java.lang.SecurityException: Starting FGS with type microphone callerApp=ProcessRecord{628de8f 11525:com.whistle.dev/u0a272} targetSDK=34 requires permissions: all of the permissions allOf=true [android.permission.FOREGROUND_SERVICE_MICROPHONE] any of the permissions allOf=false [android.permission.CAPTURE_AUDIO_HOTWORD, android.permission.CAPTURE_AUDIO_OUTPUT, android.permission.CAPTURE_MEDIA_OUTPUT, android.permission.CAPTURE_TUNER_AUDIO_INPUT, android.permission.CAPTURE_VOICE_COMMUNICATION_OUTPUT, android.permission.RECORD_AUDIO]  and the app must be in the eligible state/exemptions to access the foreground only permission
  android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4880)
