### ISSUE TITLE
How to make incoming call notification priority on android.

### ISSUE THREAD

**Issue by prototypeninja** [twilio/twilio-voice-react-native#337]
# Issue

## Pre-submission Checklist
- [yes ] I have verified that the issue occurs with the latest release and is not marked as a known issue in the [CHANGELOG.md](https://github.com/twilio/twilio-voice-react-native/blob/main/CHANGELOG.md).
- [yes ] I reviewed the [Common Issues](https://github.com/twilio/twilio-voice-react-native/blob/main/COMMON_ISSUES.md) and open GitHub issues and verified that this report represents a potentially new issue.
- [ yes] I am not sharing any [Personally Identifiable Information (PII)](https://www.twilio.com/docs/glossary/what-is-personally-identifiable-information-pii)
       or sensitive account information (API keys, credentials, etc.) when reporting this issue.

## Description 
A clear and concise description of what the issue is.

I would like to know how to do so that when I receive an incoming call on Android the notification is displayed in the foreground like on WhatsApp, when the application is in the foreground as background or close

## Reproduction Steps
Trying to receive an incoming call on Android, you will see that the notification is hidden and does not appear in priority or foreground like WhatsApp.

## Actual Behavior
What actually happens.

## Reproduction Frequency
Is the reproducibility of the issue deterministic? If not, what percentage of the time does the issue occur? In how many attempts was the issue observed?

## Software and Device Information
**Please complete the following information.**
 - Device: android 13
 - OS: Android API Level 31
 - React version: 18.2.0
 - React Native version:0.73.4
 - Node version: 18
 - npm or yarn version: npm
 - "@twilio/voice-react-native-sdk": "^1.0.0-rc8",

**Comment by afalls-twilio** [comment]
@prototypeninja By design, we have if the application is in the foreground, it will not make the notification highest priority. if you would like the notification to be a priority, it will take a little java work.. (not much..). just modify the channel [here](https://github.com/twilio/twilio-voice-react-native/blob/4920d305ac2ceafcf342d87ee2b513f84ac449b4/android/src/main/java/com/twiliovoicereactnative/VoiceService.java#L279)  from VOICE_CHANNEL_DEFAULT_IMPORTANCE to VOICE_CHANNEL_HIGH_IMPORTANCE.

**Comment by prototypeninja** [comment]
Thank you so much,
that works
