### ISSUE TITLE
How do you cancel an outgoing call attempt before it gets connected?

### ISSUE THREAD

**Issue by marcinnexudus** [twilio/twilio-voice-react-native#396]
## Pre-submission Checklist
- [x] I have verified that the issue occurs with the latest release and is not marked as a known issue in the [CHANGELOG.md](https://github.com/twilio/twilio-voice-react-native/blob/main/CHANGELOG.md).
- [x] I reviewed the [Common Issues](https://github.com/twilio/twilio-voice-react-native/blob/main/COMMON_ISSUES.md) and open GitHub issues and verified that this report represents a potentially new issue.
- [x] I am not sharing any [Personally Identifiable Information (PII)](https://www.twilio.com/docs/glossary/what-is-personally-identifiable-information-pii)
       or sensitive account information (API keys, credentials, etc.) when reporting this issue.

## Description 
I'm trying to find a way to interrupt / cancel an outgoing call attempt before it gets connected (while the call status is 'ringing'). The Call.disconnect() method appears to only work after the call gets connected.

## Software and Device Information
**Please complete the following information.**
 - Device: n/a
 - OS: Android 14 / iOS 17
 - React version: 18.3.1
 - React Native version: 0.74.3
 - Node version: 20.4.0
 - npm or yarn version: 4.3.0

**Comment by mhuynh5757** [comment]
Hi @marcinnexudus thanks for reaching out. Are you using the `answerOnBridge` TwiML attribute? If so, then your ringing state will persist until the other client/PSTN leg picks up the call. During which, `call.disconnect` will function to "cancel" the outgoing call. Otherwise, if you are not using `answerOnBridge`, the ringing state will be very brief, and will transition to "connected" almost immediately. At this point, the other client leg might not actually have picked up the call. However, `call.disconnect` will still work.

**Comment by marcinnexudus** [comment]
Hi @mhuynh5757 Thanks for the reply. Yes, we're using `answerOnBridge`. We've managed to sort the problem. Thanks.
