### ISSUE TITLE
Improve undefined contactHandle logic

### ISSUE THREAD

**Issue by DiazIgnacio** [twilio/twilio-voice-react-native#441]
https://github.com/twilio/twilio-voice-react-native/blob/c83435fa2754e56ee8f38e3d2fdf2e46fd12cfc0/src/Voice.tsx#L319-L320

Either make param contactHandle not optional or improve undefined check validation to not only take into account empty strings but undefined as well.

**Comment by mhuynh5757** [comment]
Hey @DiazIgnacio just checking in with you on this feature request. I added an additional check to our ternary operator such that
```
const parsedContactHandle =
  contactHandle === '' || typeof contactHandle === 'undefined'
    ? 'Default Contact'
    : contactHandle;
```
However, looking over the code, it shouldn't be possible that `typeof contactHandle === 'undefined'` in this method since we have a default value of `'Default Contact'` in the `voice.connect` method signature. Let me know what you think, am I missing your particular use case?

**Comment by mhuynh5757** [comment]
For clarification, if I invoke `voice.connect(token)` (note that I do not pass any options object at all), then it should default to `Default Contact`. If I invoke `voice.connect(token, {})` it should also default, and if I do `voice.connect(token, { params: ... })` it will also default.

**Comment by DiazIgnacio** [comment]
Hey @mhuynh5757 I've came up with the same conclusion as you, thanks anyways!

**Comment by mhuynh5757** [comment]
Ah, good to hear. I will close this issue for now, please feel free to reopen if there's an edge case that is missing.
